### ISSUE TITLE
CI functional tests sporadically fail with an HTTP 500 error

### ISSUE THREAD

**Issue by mikedep333** [pulp/pulp_ansible#1274]
Multiple functional tests (within pulp/s3/azure/stream) sporadically fail with an HTTP 500 error.

https://github.com/pulp/pulp_ansible/actions/runs/3231999836/jobs/5292126376#step:13:2459

The logs do not seem to indicate why.

I am trying to reproduce it by running a tmux sessioin, and hitting ctrl+c on the tests once the error is reproduced.

**Comment by gerrod3** [comment]
I think I found the root cause of this issue explained here: https://github.com/pulp/pulpcore/issues/3299#issuecomment-1276669352. We got a race condition present, but we can remove the race in pulp_ansible as well by not creating unnecessary repository versions during the delete task. @mikedep333 I'm going to open a pulp_ansible PR with this change and attach it to this issue.
